import type { Metadata } from "next";

import NavigationBar from "@/components/NavigationBar";

import { Container } from "@mui/material";

import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavigationBar />
        <Container
          maxWidth="lg"
          sx={{
            display: "flex",
            flexDirection: "column",
            paddingTop: 11,
          }}
        >
          {children}
        </Container>
      </body>
    </html>
  );
}
